name: pulsebrew
description: AI-powered coffee companion
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  health: ^13.2.1
  device_info_plus: ^12.3.0
  shared_preferences: ^2.4.0
  sqflite: ^2.4.1
  path_provider: ^2.1.4
  http: ^1.2.2
  flutter_blue_plus: ^2.1.0
  uuid: ^4.4.0
  http: ^1.2.0


flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
